# Generated by Django 5.2.8 on 2026-01-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_bank_rule_auto_categorize_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companionissue',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='business',
            name='tax_filing_due_day',
        ),
        migrations.RemoveField(
            model_name='business',
            name='tax_filing_frequency',
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='estimated_impact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='recommended_action',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='run_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='run_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='surface',
            field=models.CharField(choices=[('receipts', 'Receipts'), ('invoices', 'Invoices'), ('books', 'Books'), ('bank', 'Bank'), ('tax', 'Tax')], db_index=True, default='books', max_length=20),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='companionissue',
            index=models.Index(fields=['business', 'status'], name='core_compan_busines_5da70b_idx'),
        ),
        migrations.AddIndex(
            model_name='companionissue',
            index=models.Index(fields=['business', 'surface'], name='core_compan_busines_c2bad5_idx'),
        ),
        migrations.AddIndex(
            model_name='companionissue',
            index=models.Index(fields=['business', 'severity'], name='core_compan_busines_819cc6_idx'),
        ),
    ]
